// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: rwsafeuaonnqadhdwpkl

class SupabaseConfig {
  static const String supabaseUrl = 'https://rwsafeuaonnqadhdwpkl.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3c2FmZXVhb25ucWFkaGR3cGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MjE4ODMsImV4cCI6MjA3OTA5Nzg4M30.Buv1oPAUMjb9bA-1bNNE6TAOElhttA6hV55kFb8aSX8';
}
